apiVersion: v1
kind: Pod
metadata:
  name: nginx-prince
  labels:
    app: nginx-prince
spec:
  containers:
    - name: main-ctr
      image: nigelpoulton/nginxadapter:1.0
      ports:
        - containerPort: 80

    - name: helper-ctr
      image: nginx/nginx-prometheus-exporter
      args: ["-nginx.scrape-uri", "http://localhost/nginx_status"]
      ports:
        - containerPort: 9113

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx-prince
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8099
      nodePort: 30080

